name: MRI Windows

on: [push, pull_request, workflow_dispatch]

jobs:
  mri_windows:
    name: >-
      ${{ matrix.os }}  ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2025, windows-2022 ]
        ruby: [ head, 3.4, 3.3, 3.2, 3.1, '3.0', 2.7, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, '2.0' ]
        include:
          - { os: windows-2022  , ruby: mingw }
          - { os: windows-2022  , ruby: mswin }
          - { os: windows-2025  , ruby: ucrt  }
          - { os: windows-11-arm, ruby: head  }
          - { os: windows-11-arm, ruby: 3.4   }

    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: set ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - name: Ruby Info
        run:  ruby ruby_info.rb

      - name: Ruby libyaml bug
        run:  ruby libyaml_trailing_space.rb

      - name: Windows ridk version
        if:   matrix.ruby > '2.3' && matrix.ruby != 'mswin'
        run:  ridk version
