name: MRI macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  mri_macos:
    name: >-
      ${{ matrix.os }}  ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-26, macos-15, macos-15-intel, macos-14 ]
        ruby: [ head, 3.4, 3.3, 3.2, 3.1, '3.0', 2.7, 2.6, 2.5, 2.4 ]
        exclude:
          #macos 14 and 15 (arm), only test Ruby 2.6 and later
          - { os: macos-14     , ruby:  2.4  }
          - { os: macos-14     , ruby:  2.5  }
          - { os: macos-15     , ruby:  2.4  }
          - { os: macos-15     , ruby:  2.5  }
          - { os: macos-15     , ruby:  2.6  }
          - { os: macos-26     , ruby:  2.4  }
          - { os: macos-26     , ruby:  2.5  }
          - { os: macos-26     , ruby:  2.6  }

    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: set ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - name: Ruby Info
        run:  ruby ruby_info.rb

      - name: Ruby libyaml bug
        run:  ruby libyaml_trailing_space.rb
