name: Non MRI Ruby

on: [push, pull_request, workflow_dispatch]

jobs:
  non_mri:
    name: >-
      ${{ matrix.os }}  ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04  , ruby: jruby            }
          - { os: ubuntu-24.04  , ruby: jruby-head       }
          - { os: ubuntu-24.04  , ruby: truffleruby      }
          - { os: ubuntu-24.04  , ruby: truffleruby-head }
          - { os: ubuntu-22.04  , ruby: jruby            }
          - { os: ubuntu-22.04  , ruby: jruby-head       }
          - { os: ubuntu-22.04  , ruby: truffleruby      }
          - { os: ubuntu-22.04  , ruby: truffleruby-head }
          - { os: macos-26      , ruby: jruby            }
          - { os: macos-15      , ruby: jruby            }
          - { os: macos-15-intel, ruby: jruby            }
          - { os: macos-14      , ruby: jruby            }
          - { os: macos-26      , ruby: jruby-head       }
          - { os: macos-15      , ruby: jruby-head       }
          - { os: macos-15-intel, ruby: jruby-head       }
          - { os: macos-26      , ruby: truffleruby      }
          - { os: macos-15      , ruby: truffleruby      }
          - { os: macos-15      , ruby: truffleruby-head }
          - { os: macos-15-intel, ruby: truffleruby      }
          - { os: macos-15-intel, ruby: truffleruby-head }
          - { os: macos-14      , ruby: truffleruby      }
          - { os: macos-14      , ruby: truffleruby-head }
          - { os: windows-2022  , ruby: jruby }

    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: set ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - name: Ruby Info
        run:  ruby ruby_info.rb

      - name: Ruby libyaml bug
        run:  ruby libyaml_trailing_space.rb
