# 2019-12-18 Update
name: Actions Ruby

on: [push]

jobs:
  build:
    name: >-
      ${{ matrix.ruby }}  ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-16.04', 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        ruby: [ '2.4.x', '2.5.x', '2.6.x' ]

    steps:
    - name: repo checkout
      uses: actions/checkout@v2

    - name: set ruby version
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Ruby Info
      run:  ruby ruby_info.rb

    - name: Add MSYS2 paths
      uses: MSP-Greg/msys2-action/add_paths@master
      if:   matrix.os == 'windows-latest'

    - name: MSYS2 Package Info
      run: |
        ridk version
        ruby pacman_query.rb
      if:   matrix.os == 'windows-latest'
