# 2020-08-30 Update
name: Actions Ruby

on: [push]

jobs:
  build:
    name: >-
      ${{ matrix.ruby }}  ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-latest, windows-latest ]
        ruby: [ 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, head ]
        include:
          - { os: windows-latest , ruby: mingw }
          - { os: windows-latest , ruby: mswin }

    steps:
    - name: repo checkout
      uses: actions/checkout@v2

    - name: set ruby version
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Ruby Info
      run:  ruby ruby_info.rb

    - name: MSYS2 Package Info
      if:   matrix.os == 'windows-latest' && matrix.ruby > '2.3'
      run:  |
        ridk version
        ruby pacman_query.rb
