name: Actions Ruby

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: >-
      ${{ matrix.os }}  ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04, macos-11.0, macos-10.15, windows-2019, windows-2022 ]
        ruby: [ head, 3.1, '3.0', 2.7, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, '2.0' ]
        include:
          - { os: ubuntu-20.04 , ruby: jruby-9.2.9.0    }
          - { os: ubuntu-20.04 , ruby: truffleruby      }
          - { os: ubuntu-20.04 , ruby: truffleruby-head }
          - { os: ubuntu-22.04 , ruby: 3.1  }
          - { os: ubuntu-22.04 , ruby: head }
          - { os: windows-2019 , ruby: mingw }
          - { os: windows-2019 , ruby: mswin }
          - { os: windows-2022 , ruby: ucrt  }
        exclude:
          - { os: windows-2019 , ruby:  2.1  }
          - { os: windows-2019 , ruby: '2.0' }

    steps:
      - name: repo checkout
        uses: actions/checkout@v3

      - name: set ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - name: Ruby Info
        run:  ruby ruby_info.rb

      - name: Ruby libyaml bug
        run:  ruby libyaml_trailing_space.rb

      - name: Windows ridk version
        if:   startsWith(matrix.os, 'windows') && matrix.ruby > '2.3' && matrix.ruby != 'mswin'
        run:  ridk version
