name: Actions Ruby

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: >-
      ${{ matrix.os }}  ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-14, macos-13, macos-12, macos-11, windows-2022, windows-2019 ]
        ruby: [ head, 3.3, 3.2, 3.1, '3.0', 2.7, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, '2.0' ]
        include:
          - { os: ubuntu-20.04 , ruby: jruby            }
          - { os: ubuntu-20.04 , ruby: truffleruby      }
          - { os: ubuntu-20.04 , ruby: truffleruby-head }
          - { os: ubuntu-22.04 , ruby: jruby            }
          - { os: ubuntu-22.04 , ruby: truffleruby      }
          - { os: ubuntu-22.04 , ruby: truffleruby-head }
          - { os: ubuntu-24.04 , ruby: jruby            }
          - { os: ubuntu-24.04 , ruby: truffleruby      }
          - { os: ubuntu-24.04 , ruby: truffleruby-head }
          - { os: macos-14     , ruby: jruby            }
          - { os: macos-14     , ruby: truffleruby      }
          - { os: macos-14     , ruby: truffleruby-head }
          - { os: windows-2019 , ruby: mingw }
          - { os: windows-2019 , ruby: mswin }
          - { os: windows-2022 , ruby: ucrt  }
          - { os: windows-2022 , ruby: jruby }
        exclude:
          - { os: ubuntu-24.04 , ruby: '3.0' }
          - { os: ubuntu-24.04 , ruby:  2.7  }
          - { os: ubuntu-24.04 , ruby:  2.6  }
          - { os: ubuntu-24.04 , ruby:  2.5  }
          - { os: ubuntu-24.04 , ruby:  2.4  }
          - { os: ubuntu-24.04 , ruby:  2.3  }
          - { os: ubuntu-24.04 , ruby:  2.2  }
          - { os: ubuntu-24.04 , ruby:  2.1  }
          - { os: ubuntu-24.04 , ruby: '2.0' }
          - { os: windows-2019 , ruby:  2.1  }
          - { os: windows-2019 , ruby: '2.0' }
          - { os: windows-2022 , ruby:  2.1  }
          - { os: windows-2022 , ruby: '2.0' }
          - { os: macos-14     , ruby: '2.0' }
          - { os: macos-14     , ruby:  2.1  }
          - { os: macos-14     , ruby:  2.2  }
          - { os: macos-14     , ruby:  2.3  }
          - { os: macos-14     , ruby:  2.4  }
          - { os: macos-14     , ruby:  2.5  }

    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: set ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - name: Ruby Info
        run:  ruby ruby_info.rb

      - name: Ruby libyaml bug
        run:  ruby libyaml_trailing_space.rb

      - name: Windows ridk version
        if:   startsWith(matrix.os, 'windows') && matrix.ruby > '2.3' && matrix.ruby != 'mswin' && !startsWith(matrix.ruby, 'jruby')
        run:  ridk version
