# 2020-06-28 Update
name: Actions Ruby

on: [push]

jobs:
  build:
    name: >-
      ${{ matrix.ruby }}  ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-16.04', 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        ruby: [ '2.3', '2.4', '2.5', '2.6', '2.7' ]

    steps:
    - name: repo checkout
      uses: actions/checkout@v2

    - name: set ruby version
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Ruby Info
      run:  ruby ruby_info.rb

    - name: MSYS2 Package Info
      if:   matrix.os == 'windows-latest'
      run:  |
        ridk version
        ruby pacman_query.rb
